---
# file: roles/common/tasks/main.yml
# Tasks common to all nodes

- name: update apt-get
  apt: update_cache=yes cache_valid_time=300

- name: install required software
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - sudo

- name: setup app user
  user: name="{{ app_user }}" shell=/bin/bash groups=www-data

- name: add application user to core groups
  user: name="{{ app_user }}" group=www-data groups="{{ item }}" append=yes shell=/bin/bash
  with_items:
    - www-data
    - staff
    - sudo

- name: give app user passwordless sudo
  lineinfile: dest=/etc/sudoers state=present line="{{ app_user }}    ALL=(ALL) NOPASSWD:ALL"

- name: default login shell to app's source
  lineinfile: dest=/root/.bashrc line="cd {{ app_path }}" 

- name: setup an authorized key for root
  authorized_key: user=root key="{{ item }}" state=present 
  with_file:
    - public_keys/id_rsa.pub
  notify: restart ssh

- name: setup an authorized key for app user
  authorized_key: user={{ app_user }} key="{{ item }}" state=present 
  with_file:
    - public_keys/id_rsa.pub
  notify: restart ssh  

- name: disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no"
  notify: restart ssh

- name: disable legacy systemd script
  service: name="{{ app_name }}.target" enabled=no state=stopped
  register: command_result
  failed_when: "command_result | failed and 'could not find' not in command_result.msg"
  
- name: set default present working directory (PWD)
  lineinfile: dest="{{ item }}/.bashrc" line="cd {{ app_path }}"
  with_items:
    - /root
    - "/home/{{ app_user }}"