---
# file: roles/app_web_server/tasks/main.yml

- name: clone or update source
  git:
    repo: "{{ git_url }}"
    version: "{{ git_branch }}"
    dest: "{{ app_path }}"
    update: yes
    accept_hostkey: yes
    force: yes

- name: install dependencies
  bundler: state=present chdir="{{ app_path }}"

- name: precompile assets
  shell: "`which bundle` exec rails assets:clean assets:precompile"
  args:
    chdir: "{{ app_path }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"

- name: migrate database
  shell: "`which bundle` exec rails db:migrate"
  args:
    chdir: "{{ app_path }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"

- name: create foreman config
  template: src=foreman_config.j2 dest="{{ app_path }}/.foreman" mode=0644
  become: yes
  
- name: export rails env variables
  template: src=rails_env.sh.j2 dest=/etc/profile.d/rails_env.sh mode=0644
  become: yes

- name: create systemd script
  shell: bundle exec foreman export systemd /etc/systemd/system -a {{ app_name }} -u root
  args:
    chdir: "{{ app_path }}"
    creates: "/etc/systemd/{{ app_name }}.target"

- name: enable systemd script
  service: name="{{ app_name }}.target" enabled=yes

- name: restart server
  service: name="{{ app_name }}.target" state=restarted