---
- include: common.yml

- name: deploy and configure rvm 
  hosts: web_servers
  remote_user: root
  roles: 
    - rvm_io.rvm1-ruby

- include: app_setup.yml

- include: app_web_server.yml
