---
rails_env: production
secret_key_base: 3c8d5ffea53ce05c3d481e9a12c516f94c9dda2d38210d65f55e90b0813819348c7fd7c1f7a6969f8950ce76e6e1de72196616f58dad7a073ed86c9b5ac572fc

# TODO: Move to seperate server main_db_server: 159.203.30.99
main_db_server: localhost

main_web_server: 159.203.14.69
server_name: "{{ main_web_server }}"

db_rails_username: rails
db_rails_password: testtemp
db_rails_port: 5432
db_rails_name: workshop_app